baseURL = "http://example.org/"
languageCode = "en-us"
title = "μdocs"
theme = "Dot"

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#5feff9"
body_color = "#361a99"
text_color = "#8ca4b4"
text_color_dark = "#ffffff"
white_color = "#171b42"
light_color = "#361a99"

# font family
font_family = "roboto" # Choose font family from : https://fonts.google.com/

################################ English Language ######################
[Languages.en]
weight = 1

# banner
[Languages.en.params.banner]
title = "μdocs for mutant"
subtitle = "mutant is an open source programming language whose aim is to provide an accessible, secure way for programming & security research."
bg_image = "images/banner.jpeg"

# call to action
[Languages.en.params.cta]
enable = true
title = "Download latest binaries here"
content = "Official compiled binaries are available for: Linux, macOS, & Windows"

# call to action button
[Languages.en.params.cta.button]
enable = true
label = "Download"
link = "https://github.com/gaurav-gogia/mutant"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

# Dropdown menu
[[Languages.en.menu.main]]
weight = 2
name = "docs"
hasChildren = true

[[Languages.en.menu.main]]
parent = "docs"
name = "Features"
url = "docs/features"
weight = 1

[[Languages.en.menu.main]]
parent = "docs"
name = "Language Docs"
url = "docs/languagedocs"
weight = 2

[[Languages.en.menu.main]]
parent = "docs"
name = "Examples"
url = "docs/examples"
weight = 3

[[Languages.en.menu.main]]
name = "About Us"
url = "about"
weight = 3

[[Languages.en.menu.main]]
name = "Faq"
url = "faq"
weight = 4
